In [66]:
import numpy as np

In [67]:
np.__version__

'2.4.6'

In [68]:
fruits = np.array(['Mango','Strawberry','Apple','Dates','Watermelon'])
fruits.ndim

1

In [69]:
# Slicing from start to all
fruits[0:]

array(['Mango', 'Strawberry', 'Apple', 'Dates', 'Watermelon'],
      dtype='<U10')

In [70]:
# Slicing form second element to third element include
fruits[1:3]

array(['Strawberry', 'Apple'], dtype='<U10')

In [71]:
# Slicing from second element to all and step 2
fruits[1::2]

array(['Strawberry', 'Dates'], dtype='<U10')

In [72]:
# multi dimensional
scores = np.array([
    [12,33,30],
    [91,77,88],
    [12,14,99],
    [56,91,100]
])
# four rows and three columns
scores.ndim

2

In [73]:
# display first students seconds score number.
scores[0,1]

np.int64(33)

In [74]:
# display each students third subject score number
scores[:,2]

array([ 30,  88,  99, 100])

In [75]:
# display last students score numbers but steps 2
scores[3,::2]

array([ 56, 100])

In [76]:
# display students score number steps 2 both students and scores
scores[::2,::2]

array([[12, 30],
       [12, 99]])

In [77]:
# three dimensional array
groups = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12],
        ]
    ]
)
groups.ndim

3

In [78]:
# display first groups teams
groups[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# display first groups team members steps 2
groups[0,:,::2]

array([[1, 3],
       [4, 6]])

In [80]:
# display second group teams steps 2
groups[1,::2]

array([[7, 8, 9]])